spring.application.name=bff-agendador
usuario.url = localhost:8080/usuario
agendador-tarefas.url = localhost:8081/tarefa
server.port=8085
notificacao.url=localhost:8083/email
usuario.email= admin@admin.com
usuario.senha= 1234
cron.horario=0 0/5 * * * ?